CREATE TABLE tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL UNIQUE,
    PRIMARY KEY (id)
);

CREATE TABLE discoveries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    streetAddress VARCHAR(255),
    city VARCHAR(255),
    country VARCHAR(255),
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    user_email VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE discovery_tags (
    discovery_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,
    PRIMARY KEY (discovery_id, tag_id),
    FOREIGN KEY (discovery_id) REFERENCES discoveries(id),
    FOREIGN KEY (tag_id) REFERENCES tags(id)
);
